sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js: lts/*
env:
  global:
  - secure: GdZ5v0iDY+U48KMewcP1V3O+HkORzKGWj4w5Ol/wRyjf/W6GgfdhcYqzBB1lUPpc2bnftmAe4OHmUchMpNo43jkytL3B/OCQ23OQ9hEqm3Jo4ghAe7rucBNMjT/2+Wlbjsx8t0n+bFkFr+/FcbHlzD7WsHqIGZW4r46oiONQ5uzbSR9LMkzJW6igfNHONsx/Aog6E9Yx68zJI6sS1D9Je4JtOWm/SBy2esfuqYkneXRN2t7TKoB0upFhC1bExO8bJaRHWi3h4HbNb4Me0Oz92zs1pAtAcFxKptgXlAbzedeVskaNmN9TiVV8pHv8J/X85n56y2xptCCGImM6GZWATY3zlpkSVrnA645CMgJDDUlzi9KMvt/7AaLKFKvUrVz1Ady/fvKyyhAYBOh106JlcMRZLICy/U4ZvVy/oBFZtEiYDuwtge/2NR83VOkDN+NFws2QI6tjI6Zd5i15Mmdt1WIEK+LsXcVn3ngu/4dNu/hW3FKWSRD7X4U6skC4Vn9IXjtn7gFzRhnYVNiECN09+0BbLcn1rKqop5UsAFC2RmJsOVV4KosUYlfHkGPpJSRZsokk2D4lCZ7mqU8qDG+wKRF6Y/0zs7hmRWZLM0uTfWoAtYzwex/Bj5qFZhoWJuse5ZTnY3HnRVQf0HBzwcp7tJ04V0DSl5aahw04iVoI0HI=
stages:
- test
- name: deploy
jobs:
  include:
  - stage: Test
    name: lint
    script:
    - yarn lint
  - script:
    - yarn test
    name: test
  - script:
    - yarn build-storybook
    name: build storybook
  - stage: deploy
    name: deploy to gh-page
    env: gh-page
    script:
    - yarn build-storybook
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      local-dir: storybook-static
      on:
        branch: master
